<div class="jumbotron">
    
    <form action="<?php echo $this->url('home') ?>" method="post">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="from">Kaynak Dil</label> <select id="from" class="form-control" name="from">
                        <option value="detect">Dili Algıla</option>
                        <?php foreach ($languages as $language) { ?>
                            <option value="<?php echo $language['language']; ?>" <?php echo $language['language'] == $source ? 'selected' : null; ?>>
                                <?php echo $language['name']; ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="text">Metin</label>
                    <textarea class="form-control" id="text" name="text" rows="3"><?php echo $text; ?></textarea>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="target">Hedef Dil</label> <select id="target" class="form-control" name="target">
                        <?php foreach ($languages as $language) { ?>
                            <option value="<?php echo $language['language']; ?>" <?php echo $language['language'] == $target ? 'selected' : null; ?>>
                                <?php echo $language['name']; ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="result">Çeviri</label>
                    <ul class="list-group" id="result">
                        <?php foreach ($translations as $translation) { ?>
                            <li class="list-group-item">
                                <?php echo \Application\View\Helper\Highlight::make($text, $translation['translatedText']); ?>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="float-right">
                    <button type="submit" class="btn btn-outline-primary">Çevir</button>
                </div>
            </div>
        </div>
    </form>

</div>


